name: Upload Lambda to S3
 
on:
  push:
    branches:
      - main
 
jobs:
  deploy:
    runs-on: ubuntu-latest
 
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
 
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
 
    - name: Zip the lambda function
      run: |
        zip hello.zip hello.py
        zip cost-explorer.zip cost-explorer.py
 
    - name: Upload to S3
      run: |
        aws s3 cp hello.zip s3://lambda-stored/
        aws s3 cp cost-explorer.zip s3://lambda-stored/